### ISSUE TITLE
Copy-Paste

### ISSUE THREAD

**Issue by GScripKa** [builtbybel/SuperMSConfig#14]
my English is bad...
How can I highlight and copy the text (parameter name) to open it in translator or Google search to get more information?
Add a text selection function

**Comment by Belim** [comment]
Just use the built-in copilot plugin for this 😃  Here’s a quick presentation

https://github.com/user-attachments/assets/f2f89192-eb9a-4daa-983d-0016980296f0

**Comment by GScripKa** [comment]
![2024-09-27_004935](https://github.com/user-attachments/assets/3209bb86-9925-4b29-b684-a24070c3f65e)
I would also like to be able to highlight and copy understandable text.

**Comment by Belim** [comment]
Oh right, I'll activate that too, good point

**Comment by Belim** [comment]
The new versions have got this covered now
