### ISSUE TITLE
W10 The program does not start

### ISSUE THREAD

**Issue by Brindemosporelcaracter** [builtbybel/SuperMSConfig#16]
Nombre de la aplicación con errores: SuperMSConfig.exe, versión: 1.3.1.0, marca de tiempo: 0x93d87340
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.4842, marca de tiempo: 0xe6d00f33
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000003b699
Identificador del proceso con errores: 0x1554
Hora de inicio de la aplicación con errores: 0x01db10bf4ec95857
Ruta de acceso de la aplicación con errores: C:\SuperMSConfig\SuperMSConfig.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: a6407df2-991e-4228-89c7-0ce69808f6ed
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores: 
Aplicación: SuperMSConfig.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.IO.FileNotFoundException
   en PluginLoader.LoadAllPlugins()
   en PluginLoader..ctor(System.Windows.Forms.Panel, System.Windows.Forms.ContextMenuStrip)
   en SuperMSConfig.Wrapper.InitializePluginLoader()
   en SuperMSConfig.Wrapper..ctor()
   en SuperMSConfig.Program.Main()

I hope you find a solution, I tried but I couldn't, the previous versions worked correctly, I don't know if this new version was made exclusively for Windows 11

**Comment by Belim** [comment]
Could you please try removing the pluginCopilot folder from the plugins directory and test it without it?

**Comment by ImhofMarkus** [comment]
Test
- removed Copilot Plugin Folder: program does not start
- removed MSNavigator Plugin Folder: program does not start
- removed MSCleanupCompanion Plugin Folder: program does not start
- removed all Plugins: program start

**Comment by Brindemosporelcaracter** [comment]
Issue solved, you have to delete the folder, plugins
thank you so much

**Comment by Belim** [comment]
Unfortunately, that's not a solution 😅 does this affect you as well? 


https://github.com/builtbybel/SuperMSConfig/issues/15#issuecomment-2379009451

**Comment by Belim** [comment]
Build 1.3.1.19 fixes the issue that prevented the Copilot plugin from being called up https://github.com/builtbybel/SuperMSConfig/releases/tag/1.3.1
