### ISSUE TITLE
serious mistake

### ISSUE THREAD

**Issue by Brindemosporelcaracter** [builtbybel/SuperMSConfig#20]
It does NOT allow changes made by the application to be reverted

qtorrent, supermsconfig, does not want it to start with the system and there is no way to reverse it, the advice it gives, doing it from the same application does not work

Another question, read application that I do not have installed on my system, services, etc., I suppose that is what the program is like (supermsconfig, right?) thank you very much

![6-10-2024 9 10 32 1](https://github.com/user-attachments/assets/a8962ce1-9ba0-4870-b46f-1f7fabfc5c3a)

**Comment by Belim** [comment]
These areas have already been fixed for you, and a revert is not supported for the "Startup" and "Apps" tabs. Please update to version 1.5 everything looks much sleeker there
